const administrations = [
    { id: "ADM-1000", name: "وزارة الداخلية", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537221144" },
    { id: "ADM-1001", name: "وزارة الشؤون الخارجية والتعاون الإفريقي", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537762211" },
    { id: "ADM-1002", name: "وزارة العدل", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537733333" },
    { id: "ADM-1003", name: "وزارة الأوقاف والشؤون الإسلامية", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537763210" },
    { id: "ADM-1004", name: "الأمانة العامة للحكومة", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537764455" },
    { id: "ADM-1005", name: "وزارة الاقتصاد والمالية", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537765566" },
    { id: "ADM-1006", name: "وزارة التجهيز والماء", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537766677" },
    { id: "ADM-1007", name: "وزارة التربية الوطنية والتعليم الأولي والرياضة", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537777788" },
    { id: "ADM-1008", name: "وزارة الصحة والحماية الاجتماعية", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537788899" },
    { id: "ADM-1009", name: "وزارة إعداد التراب الوطني والتعمير", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537799900" },
    { id: "ADM-1010", name: "وزارة الفلاحة والصيد البحري", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537711122" },
    { id: "ADM-1011", name: "وزارة الإدماج الاقتصادي والمقاولة الصغرى والتشغيل", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537722233" },
    { id: "ADM-1012", name: "وزارة الصناعة والتجارة", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537733344" },
    { id: "ADM-1013", name: "وزارة السياحة والصناعة التقليدية", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537744455" },
    { id: "ADM-1014", name: "وزارة التعليم العالي والبحث العلمي", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537755566" },
    { id: "ADM-1015", name: "وزارة الانتقال الطاقي والتنمية المستدامة", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537766677" },
    { id: "ADM-1016", name: "وزارة النقل واللوجيستيك", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537777788" },
    { id: "ADM-1017", name: "وزارة الشباب والثقافة والتواصل", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537788899" },
    { id: "ADM-1018", name: "وزارة التضامن والإدماج الاجتماعي", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537799900" },
    { id: "ADM-1019", name: "إدارة الدفاع الوطني", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537711111" },
    { id: "ADM-1020", name: "الوزارة المنتدبة المكلفة بالاستثمار", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537722222" },
    { id: "ADM-1021", name: "الوزارة المكلفة بالعلاقات مع البرلمان", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537733333" },
    { id: "ADM-1022", name: "الوزارة المكلفة بالميزانية", category: "وزارات", icon: "fas fa-landmark", colorClass: "bg-blue", phone: "0537744444" },
    { id: "ADM-1023", name: "الصندوق الوطني للضمان الاجتماعي (CNSS)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0522544444" },
    { id: "ADM-1024", name: "الصندوق الوطني لمنظمات الاحتياط الاجتماعي (CNOPS)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537755555" },
    { id: "ADM-1025", name: "صندوق الإيداع والتدبير (CDG)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537766666" },
    { id: "ADM-1026", name: "المكتب الوطني للكهرباء والماء الصالح للشرب (ONEE)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0522777777" },
    { id: "ADM-1027", name: "المكتب الشريف للفوسفاط (OCP)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0522888888" },
    { id: "ADM-1028", name: "الوكالة الوطنية للمحافظة العقارية (ANCFCC)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537999999" },
    { id: "ADM-1029", name: "المكتب الوطني للسكك الحديدية (ONCF)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537111111" },
    { id: "ADM-1030", name: "الخطوط الملكية المغربية (RAM)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0522222222" },
    { id: "ADM-1031", name: "بريد المغرب (Poste Maroc)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537333333" },
    { id: "ADM-1032", name: "اتصالات المغرب (Maroc Telecom)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537444444" },
    { id: "ADM-1033", name: "الوكالة الوطنية لتقنين المواصلات (ANRT)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537555555" },
    { id: "ADM-1034", name: "الوكالة الوطنية للسلامة الطرقية (NARSA)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537666666" },
    { id: "ADM-1035", name: "الوكالة الوطنية لإنعاش التشغيل والكفاءات (ANAPEC)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0522777777" },
    { id: "ADM-1036", name: "الوكالة الوطنية لتنمية مناطق الواحات (ANDZOA)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537888888" },
    { id: "ADM-1037", name: "بنك المغرب (Bank Al-Maghrib)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537999999" },
    { id: "ADM-1038", name: "الهيئة المغربية لسوق الرساميل (AMMC)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537112233" },
    { id: "ADM-1039", name: "الوكالة المغربية لتنمية الاستثمارات (AMDIE)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537223344" },
    { id: "ADM-1040", name: "المكتب الوطني للمطارات (ONDA)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0522334455" },
    { id: "ADM-1041", name: "الشركة الوطنية للإذاعة والتلفزة (SNRT)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537445566" },
    { id: "ADM-1042", name: "وكالة المغرب العربي للأنباء (MAP)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537556677" },
    { id: "ADM-1043", name: "المندوبية السامية للتخطيط (HCP)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537667788" },
    { id: "ADM-1044", name: "المندوبية السامية للمياه والغابات", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537778899" },
    { id: "ADM-1045", name: "رادما - مراكش (RADEEMA)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0524889900" },
    { id: "ADM-1046", name: "راديج - الجديدة (RADEEJ)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0523112233" },
    { id: "ADM-1047", name: "راديف - فاس (RADEEF)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0535223344" },
    { id: "ADM-1048", name: "أمانديس - طنجة (AMENDIS)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0539334455" },
    { id: "ADM-1049", name: "ليدك - الدار البيضاء (LYDEC)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0522445566" },
    { id: "ADM-1050", name: "ريضال - الرباط (REDAL)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537556677" },
    { id: "ADM-1051", name: "مؤسسة محمد الخامس للتضامن", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537667788" },
    { id: "ADM-1052", name: "مؤسسة الحسن الثاني للمغاربة المقيمين بالخارج", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537778899" },
    { id: "ADM-1053", name: "مجلس المنافسة", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537889900" },
    { id: "ADM-1054", name: "الهيئة الوطنية للوقاية من الرشوة", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537112233" },
    { id: "ADM-1055", name: "المجلس الوطني لحقوق الإنسان (CNDH)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537223344" },
    { id: "ADM-1056", name: "مؤسسة الوسيط", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537334455" },
    { id: "ADM-1057", name: "المجلس الأعلى للحسابات", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537445566" },
    { id: "ADM-1058", name: "المجلس الاقتصادي والاجتماعي والبيئي", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537556677" },
    { id: "ADM-1059", name: "المكتب الوطني للسلامة الصحية (ONSSA)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537667788" },
    { id: "ADM-1060", name: "التعاون الوطني", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537778899" },
    { id: "ADM-1061", name: "الوكالة الوطنية للدعم الاجتماعي", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537889900" },
    { id: "ADM-1062", name: "السجل الوطني للسكان (RNP)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537112233" },
    { id: "ADM-1063", name: "الوكالة الوطنية للتأمين الصحي (ANAM)", category: "مؤسسات عمومية", icon: "fas fa-building", colorClass: "bg-green", phone: "0537223344" },
    { id: "ADM-1064", name: "ولاية جهة طنجة تطوان الحسيمة", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0539334455" },
    { id: "ADM-1065", name: "ولاية جهة الشرق", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0536445566" },
    { id: "ADM-1066", name: "ولاية جهة فاس مكناس", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0535556677" },
    { id: "ADM-1067", name: "ولاية جهة الرباط سلا القنيطرة", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0537667788" },
    { id: "ADM-1068", name: "ولاية جهة بني ملال خنيفرة", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0523778899" },
    { id: "ADM-1069", name: "ولاية جهة الدار البيضاء سطات", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0522889900" },
    { id: "ADM-1070", name: "ولاية جهة مراكش آسفي", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0524112233" },
    { id: "ADM-1071", name: "ولاية جهة درعة تافيلالت", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0535223344" },
    { id: "ADM-1072", name: "ولاية جهة سوس ماسة", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0528334455" },
    { id: "ADM-1073", name: "ولاية جهة كلميم واد نون", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0528445566" },
    { id: "ADM-1074", name: "ولاية جهة العيون الساقية الحمراء", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0528556677" },
    { id: "ADM-1075", name: "ولاية جهة الداخلة وادي الذهب", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0528667788" },
    { id: "ADM-1076", name: "عمالة الرباط", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0537778899" },
    { id: "ADM-1077", name: "عمالة سلا", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0537889900" },
    { id: "ADM-1078", name: "عمالة الصخيرات - تمارة", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0537112233" },
    { id: "ADM-1079", name: "إقليم القنيطرة", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0537223344" },
    { id: "ADM-1080", name: "إقليم الخميسات", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0537334455" },
    { id: "ADM-1081", name: "إقليم سيدي قاسم", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0537445566" },
    { id: "ADM-1082", name: "إقليم سيدي سليمان", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0537556677" },
    { id: "ADM-1083", name: "عمالة الدار البيضاء", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0522667788" },
    { id: "ADM-1084", name: "عمالة المحمدية", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0522778899" },
    { id: "ADM-1085", name: "إقليم النواصر", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0522889900" },
    { id: "ADM-1086", name: "إقليم مديونة", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0522112233" },
    { id: "ADM-1087", name: "إقليم بنسليمان", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0523223344" },
    { id: "ADM-1088", name: "إقليم برشيد", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0522334455" },
    { id: "ADM-1089", name: "إقليم سطات", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0523445566" },
    { id: "ADM-1090", name: "إقليم سيدي بنور", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0523556677" },
    { id: "ADM-1091", name: "إقليم الجديدة", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0523667788" },
    { id: "ADM-1092", name: "عمالة فاس", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0535778899" },
    { id: "ADM-1093", name: "عمالة مكناس", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0535889900" },
    { id: "ADM-1094", name: "إقليم صفرو", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0535112233" },
    { id: "ADM-1095", name: "إقليم بولمان", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0535223344" },
    { id: "ADM-1096", name: "إقليم مولاي يعقوب", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0535334455" },
    { id: "ADM-1097", name: "إقليم إفران", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0535445566" },
    { id: "ADM-1098", name: "إقليم الحاجب", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0535556677" },
    { id: "ADM-1099", name: "إقليم تازة", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0535667788" },
    { id: "ADM-1100", name: "إقليم تاونات", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0535778899" },
    { id: "ADM-1101", name: "عمالة مراكش", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0524889900" },
    { id: "ADM-1102", name: "إقليم شيشاوة", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0524112233" },
    { id: "ADM-1103", name: "إقليم الحوز", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0524223344" },
    { id: "ADM-1104", name: "إقليم قلعة السراغنة", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0524334455" },
    { id: "ADM-1105", name: "إقليم الصويرة", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0524445566" },
    { id: "ADM-1106", name: "إقليم الرحامنة", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0524556677" },
    { id: "ADM-1107", name: "إقليم آسفي", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0524667788" },
    { id: "ADM-1108", name: "إقليم اليوسفية", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0524778899" },
    { id: "ADM-1109", name: "عمالة أكادير إداوتنان", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0528889900" },
    { id: "ADM-1110", name: "عمالة إنزكان آيت ملول", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0528112233" },
    { id: "ADM-1111", name: "إقليم شتوكة آيت باها", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0528223344" },
    { id: "ADM-1112", name: "إقليم تارودانت", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0528334455" },
    { id: "ADM-1113", name: "إقليم تيزنيت", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0528445566" },
    { id: "ADM-1114", name: "إقليم طاطا", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0528556677" },
    { id: "ADM-1115", name: "عمالة طنجة أصيلة", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0539667788" },
    { id: "ADM-1116", name: "عمالة المضيق الفنيدق", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0539778899" },
    { id: "ADM-1117", name: "إقليم تطوان", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0539889900" },
    { id: "ADM-1118", name: "إقليم فحص أنجرة", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0539112233" },
    { id: "ADM-1119", name: "إقليم العرائش", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0539223344" },
    { id: "ADM-1120", name: "إقليم الحسيمة", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0539334455" },
    { id: "ADM-1121", name: "إقليم شفشاون", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0539445566" },
    { id: "ADM-1122", name: "إقليم وزان", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0539556677" },
    { id: "ADM-1123", name: "عمالة وجدة أنكاد", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0536667788" },
    { id: "ADM-1124", name: "إقليم الناظور", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0536778899" },
    { id: "ADM-1125", name: "إقليم الدريوش", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0536889900" },
    { id: "ADM-1126", name: "إقليم جرادة", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0536112233" },
    { id: "ADM-1127", name: "إقليم بركان", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0536223344" },
    { id: "ADM-1128", name: "إقليم تاوريرت", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0536334455" },
    { id: "ADM-1129", name: "إقليم جرسيف", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0536445566" },
    { id: "ADM-1130", name: "إقليم فجيج", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0536556677" },
    { id: "ADM-1131", name: "إقليم بني ملال", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0523667788" },
    { id: "ADM-1132", name: "إقليم أزيلال", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0523778899" },
    { id: "ADM-1133", name: "إقليم الفقيه بن صالح", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0523889900" },
    { id: "ADM-1134", name: "إقليم خنيفرة", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0535112233" },
    { id: "ADM-1135", name: "إقليم خريبكة", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0523223344" },
    { id: "ADM-1136", name: "إقليم الرشيدية", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0535334455" },
    { id: "ADM-1137", name: "إقليم ورزازات", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0524445566" },
    { id: "ADM-1138", name: "إقليم ميدلت", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0535556677" },
    { id: "ADM-1139", name: "إقليم تنغير", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0524667788" },
    { id: "ADM-1140", name: "إقليم زاكورة", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0524778899" },
    { id: "ADM-1141", name: "إقليم كلميم", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0528889900" },
    { id: "ADM-1142", name: "إقليم أسا الزاك", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0528112233" },
    { id: "ADM-1143", name: "إقليم طانطان", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0528223344" },
    { id: "ADM-1144", name: "إقليم سيدي إفني", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0528334455" },
    { id: "ADM-1145", name: "إقليم العيون", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0528445566" },
    { id: "ADM-1146", name: "إقليم بوجدور", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0528556677" },
    { id: "ADM-1147", name: "إقليم طرفاية", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0528667788" },
    { id: "ADM-1148", name: "إقليم السمارة", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0528778899" },
    { id: "ADM-1149", name: "إقليم وادي الذهب", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0528889900" },
    { id: "ADM-1150", name: "إقليم أوسرد", category: "عمالات وأقاليم", icon: "fas fa-map-marked-alt", colorClass: "bg-orange", phone: "0528112233" },
    { id: "ADM-1151", name: "جامعة محمد الخامس - الرباط", category: "جامعات وتعليم", icon: "fas fa-university", colorClass: "bg-purple", phone: "0537223344" },
    { id: "ADM-1152", name: "جامعة الحسن الثاني - الدار البيضاء", category: "جامعات وتعليم", icon: "fas fa-university", colorClass: "bg-purple", phone: "0522334455" },
    { id: "ADM-1153", name: "جامعة سيدي محمد بن عبد الله - فاس", category: "جامعات وتعليم", icon: "fas fa-university", colorClass: "bg-purple", phone: "0535445566" },
    { id: "ADM-1154", name: "جامعة القاضي عياض - مراكش", category: "جامعات وتعليم", icon: "fas fa-university", colorClass: "bg-purple", phone: "0524556677" },
    { id: "ADM-1155", name: "جامعة محمد الأول - وجدة", category: "جامعات وتعليم", icon: "fas fa-university", colorClass: "bg-purple", phone: "0536667788" },
    { id: "ADM-1156", name: "جامعة ابن طفيل - القنيطرة", category: "جامعات وتعليم", icon: "fas fa-university", colorClass: "bg-purple", phone: "0537778899" },
    { id: "ADM-1157", name: "جامعة عبد الملك السعدي - تطوان", category: "جامعات وتعليم", icon: "fas fa-university", colorClass: "bg-purple", phone: "0539889900" },
    { id: "ADM-1158", name: "جامعة شعيب الدكالي - الجديدة", category: "جامعات وتعليم", icon: "fas fa-university", colorClass: "bg-purple", phone: "0523112233" },
    { id: "ADM-1159", name: "جامعة ابن زهر - أكادير", category: "جامعات وتعليم", icon: "fas fa-university", colorClass: "bg-purple", phone: "0528223344" },
    { id: "ADM-1160", name: "جامعة الحسن الأول - سطات", category: "جامعات وتعليم", icon: "fas fa-university", colorClass: "bg-purple", phone: "0523334455" },
    { id: "ADM-1161", name: "جامعة مولاي إسماعيل - مكناس", category: "جامعات وتعليم", icon: "fas fa-university", colorClass: "bg-purple", phone: "0535445566" },
    { id: "ADM-1162", name: "جامعة السلطان مولاي سليمان - بني ملال", category: "جامعات وتعليم", icon: "fas fa-university", colorClass: "bg-purple", phone: "0523556677" },
    { id: "ADM-1163", name: "جامعة الأخوين - إفران", category: "جامعات وتعليم", icon: "fas fa-university", colorClass: "bg-purple", phone: "0535667788" },
    { id: "ADM-1164", name: "الجامعة الدولية للرباط", category: "جامعات وتعليم", icon: "fas fa-university", colorClass: "bg-purple", phone: "0537778899" },
    { id: "ADM-1165", name: "جامعة محمد السادس - بنجرير", category: "جامعات وتعليم", icon: "fas fa-university", colorClass: "bg-purple", phone: "0524889900" },
    { id: "ADM-1166", name: "المركز الاستشفائي الجامعي ابن سينا", category: "مستشفيات وصحة", icon: "fas fa-hospital", colorClass: "bg-red", phone: "0537112233" },
    { id: "ADM-1167", name: "المركز الاستشفائي الجامعي ابن رشد", category: "مستشفيات وصحة", icon: "fas fa-hospital", colorClass: "bg-red", phone: "0522223344" },
    { id: "ADM-1168", name: "المركز الاستشفائي الجامعي الحسن الثاني", category: "مستشفيات وصحة", icon: "fas fa-hospital", colorClass: "bg-red", phone: "0535334455" },
    { id: "ADM-1169", name: "المركز الاستشفائي الجامعي محمد السادس بمراكش", category: "مستشفيات وصحة", icon: "fas fa-hospital", colorClass: "bg-red", phone: "0524445566" },
    { id: "ADM-1170", name: "المركز الاستشفائي الجامعي محمد السادس بوجدة", category: "مستشفيات وصحة", icon: "fas fa-hospital", colorClass: "bg-red", phone: "0536556677" },
    { id: "ADM-1171", name: "المركز الاستشفائي الجامعي طنجة", category: "مستشفيات وصحة", icon: "fas fa-hospital", colorClass: "bg-red", phone: "0539667788" },
    { id: "ADM-1172", name: "المركز الاستشفائي الجامعي سوس ماسة", category: "مستشفيات وصحة", icon: "fas fa-hospital", colorClass: "bg-red", phone: "0528778899" },
    { id: "ADM-1173", name: "المستشفى العسكري محمد الخامس", category: "مستشفيات وصحة", icon: "fas fa-hospital", colorClass: "bg-red", phone: "0537889900" },
    { id: "ADM-1174", name: "مستشفى الشيخ زايد", category: "مستشفيات وصحة", icon: "fas fa-hospital", colorClass: "bg-red", phone: "0537112233" },
    { id: "ADM-1175", name: "مستشفى الشيخ خليفة", category: "مستشفيات وصحة", icon: "fas fa-hospital", colorClass: "bg-red", phone: "0522223344" },
    { id: "ADM-1176", name: "مستشفى 20 غشت", category: "مستشفيات وصحة", icon: "fas fa-hospital", colorClass: "bg-red", phone: "0522334455" },
    { id: "ADM-1177", name: "مستشفى ابن طفيل", category: "مستشفيات وصحة", icon: "fas fa-hospital", colorClass: "bg-red", phone: "0524445566" },
    { id: "ADM-1178", name: "مستشفى الرازي", category: "مستشفيات وصحة", icon: "fas fa-hospital", colorClass: "bg-red", phone: "0524556677" },
    { id: "ADM-1179", name: "مستشفى الغساني", category: "مستشفيات وصحة", icon: "fas fa-hospital", colorClass: "bg-red", phone: "0535667788" },
    { id: "ADM-1180", name: "مستشفى الفارابي", category: "مستشفيات وصحة", icon: "fas fa-hospital", colorClass: "bg-red", phone: "0536778899" },
    { id: "ADM-1181", name: "مستشفى الحسن الثاني بأكادير", category: "مستشفيات وصحة", icon: "fas fa-hospital", colorClass: "bg-red", phone: "0528889900" },
    { id: "ADM-1182", name: "محكمة النقض - الرباط", category: "محاكم وعدل", icon: "fas fa-balance-scale", colorClass: "bg-dark", phone: "0537112233" },
    { id: "ADM-1183", name: "محكمة الاستئناف بالرباط", category: "محاكم وعدل", icon: "fas fa-balance-scale", colorClass: "bg-dark", phone: "0537223344" },
    { id: "ADM-1184", name: "محكمة الاستئناف بالدار البيضاء", category: "محاكم وعدل", icon: "fas fa-balance-scale", colorClass: "bg-dark", phone: "0522334455" },
    { id: "ADM-1185", name: "محكمة الاستئناف بفاس", category: "محاكم وعدل", icon: "fas fa-balance-scale", colorClass: "bg-dark", phone: "0535445566" },
    { id: "ADM-1186", name: "محكمة الاستئناف بمراكش", category: "محاكم وعدل", icon: "fas fa-balance-scale", colorClass: "bg-dark", phone: "0524556677" },
    { id: "ADM-1187", name: "محكمة الاستئناف بطنجة", category: "محاكم وعدل", icon: "fas fa-balance-scale", colorClass: "bg-dark", phone: "0539667788" },
    { id: "ADM-1188", name: "محكمة الاستئناف بأكادير", category: "محاكم وعدل", icon: "fas fa-balance-scale", colorClass: "bg-dark", phone: "0528778899" },
    { id: "ADM-1189", name: "محكمة الاستئناف بوجدة", category: "محاكم وعدل", icon: "fas fa-balance-scale", colorClass: "bg-dark", phone: "0536889900" },
    { id: "ADM-1190", name: "محكمة الاستئناف بمكناس", category: "محاكم وعدل", icon: "fas fa-balance-scale", colorClass: "bg-dark", phone: "0535112233" },
    { id: "ADM-1191", name: "المحكمة الابتدائية بالرباط", category: "محاكم وعدل", icon: "fas fa-balance-scale", colorClass: "bg-dark", phone: "0537223344" },
    { id: "ADM-1192", name: "المحكمة الابتدائية بالدار البيضاء (الزجرية)", category: "محاكم وعدل", icon: "fas fa-balance-scale", colorClass: "bg-dark", phone: "0522334455" },
    { id: "ADM-1193", name: "المحكمة الابتدائية بالدار البيضاء (المدنية)", category: "محاكم وعدل", icon: "fas fa-balance-scale", colorClass: "bg-dark", phone: "0522445566" },
    { id: "ADM-1194", name: "محكمة الاستئناف التجارية بالدار البيضاء", category: "محاكم وعدل", icon: "fas fa-balance-scale", colorClass: "bg-dark", phone: "0522556677" },
    { id: "ADM-1195", name: "المحكمة التجارية بالدار البيضاء", category: "محاكم وعدل", icon: "fas fa-balance-scale", colorClass: "bg-dark", phone: "0522667788" },
    { id: "ADM-1196", name: "المحكمة التجارية بالرباط", category: "محاكم وعدل", icon: "fas fa-balance-scale", colorClass: "bg-dark", phone: "0537778899" },
    { id: "ADM-1197", name: "محكمة الاستئناف الإدارية بالرباط", category: "محاكم وعدل", icon: "fas fa-balance-scale", colorClass: "bg-dark", phone: "0537889900" },
    { id: "ADM-1198", name: "المحكمة الإدارية بالرباط", category: "محاكم وعدل", icon: "fas fa-balance-scale", colorClass: "bg-dark", phone: "0537112233" },
    { id: "ADM-1199", name: "المحكمة الإدارية بالدار البيضاء", category: "محاكم وعدل", icon: "fas fa-balance-scale", colorClass: "bg-dark", phone: "0522223344" }
];
